version: '3.8'

services:
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "Actividades_Complementarias"
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rust_api:
    build: .
    container_name: rust_api
    depends_on:
      - database
    ports:
      - "5050:5050"

volumes:
  db_data:
